### ISSUE TITLE
"python-adns" dependency does not exist.

### ISSUE THREAD

**Issue by joell** [trolldbois/python-cymru-services#2]
The `setup.py` file has an `extras_require` field that lists a dependency on `python-adns`.  Unfortunately, no such package exists in PyPi.  However, there is a [adns-python](https://pypi.python.org/pypi/adns-python) package.  Was this what was intended? (... or perhaps the package was renamed?)

**Comment by trolldbois** [comment]
https://packages.debian.org/unstable/python/python-adns
https://github.com/trolldbois/python3-adns

I need to check, but you are probably right, it is adns-python

**Comment by pswapneel** [comment]
Hello @trolldbois ! Thanks for building this. I know this is a very old issue but commenting here in case if this helps anyone.  On Mac OSX(adns package was already installed, else see brew install adns), I had to install the python3-adns package globally. 

Yet, to figure out a way to do this inside a virtual environment to keep it cleaner. Since the install cannot find adns.h when installing inside a virtual environment, it fails. One possible option is to add the global path of the adns.h directory inside the virtual environment in sys.path. Will give it a try in a few.
